---
output: pdf_document
fontsize: 12pt
---

\normalsize
Large microeconomic datasets are becoming increasing available in the modern world due to technological developments. These datasets provide an opportunity to improve the measurement of a range of economic phenomena and to bolster economic research. One way in which these large datasets can aid economic analysis is to create better macroeconomic indicators. 

The primary aim of this dissertation is to explore aggregation methods that overcome specific challenges in aggregating three relatively large microeconomic datasets to create macroeconomic time series indicators. The first case explores aggregation methods to estimate South African art price indices, using a relatively large database of art auction prices. The challenge in aggregating this dataset is that artworks are largely unique and infrequently traded, which means that the quality-mix of items sold is not constant over time. The chapter explores central tendency, hedonic and hybrid repeat sales methods to estimate quality-adjusted South African art price indices. 

The second case explores aggregation methods to estimate indicators of business confidence and uncertainty for South Africa, using the Bureau for Economic Research's (BER) business tendency surveys. The challenge in aggregating this dataset is to measure these nebulous concepts by identifying a pattern from the disparate views of individual agents. The chapter explores aggregation methods to capture the full distribution of the qualitative survey responses by calculating the cross-sectional weighted first and second moments of the distribution of responses. 

The third case explores aggregation methods to estimate monthly commodity price indices for the Cape Colony, using a high-frequency dataset of commodity prices in various towns in the Colony. The challenge in aggregating this dataset is that the records are incomplete with substantial gaps in the individual series. The chapter uses the repeat sales method to aggregate the incomplete records to form relatively continuous monthly wholesale commodity price indices, which reflect the mean in the distribution of growth rates.

The secondary aim of this dissertation is to use the macroeconomic indicators to test a specific hypothesis in each case. The first case studies the estimated art price indices for evidence of a bubble in South African art prices, by testing the hypothesis that South African art prices exhibited mildly explosive behaviour over the period. The second case examines the relationship between business sentiment and real activity in South Africa, by testing the hypothesis that there was significant predictive comovement between the sentiment indicators and real GDP growth. The third case studies the estimated commodity price indices, as well as other indicators, for evidence of increasing internal market integration, by testing the hypotheses of price convergence between towns and cointegration in regional price indices.

The dissertation contributes to the literature by demonstrating suitable aggregation techniques to overcome some of the challenges in aggregating relatively large datasets. These aggregation techniques may prove useful in a variety of settings where there are similar challenges. The estimated time series are reported in the appendix of each chapter. The hope is that the indicators will prove useful for further research in each of these fields. 

