---
output: 
    pdf_document:
        number_sections: true
---

#Introduction
In the modern world, technological developments are making it possible to collect increasing amounts of data on many aspects of our lives. Large microeconomic datasets provide an opportunity to improve the measurement of a range of economic phenomena and to bolster economic research [@Schutt2013]. Microeconomic data is of little use if it cannot be properly aggregated, analysed and communicated to policy makers [@Tissot2016]. The abundance of inexpensive computing power enables the processing of these large amounts of data to provide useful information and to try to distinguish the signal from the noise. 

One way in which these large amounts of microeconomic data can aid economic analysis is to construct better macroeconomic indicators. The richness of microeconomic data can assist in improving the quality and the accuracy of macroeconomic statistics [@Tissot2016]. There are always challenges in aggregating information and in identifying the underlying pattern in the data. 

This dissertation considers various challenges in aggregating microeconomic datasets and demonstrates techniques that may be useful in dealing with these challenges. The dissertation uses three relatively large microeconomic datasets to create macroeconomic time series indicators. The three datasets each have specific shortcomings, namely compositional changes, capturing the full distribution of qualitative responses, and incomplete coverage, which make it challenging to estimate time series indicators. The primary aim of this dissertation is to explore aggregation methods that overcome these specific data challenges. The dissertation demonstrates aggregation and estimation techniques, such as the hedonic and repeat sales methods and cross-sectional moments, to create useful macroeconomic indicators. 

The secondary aim of the dissertation is to use these macroeconomic indicators, as well as the underlying data, to test a specific hypothesis in each case, namely explosive South African art prices, significant predictive comovement between sentiment and real activity in South Africa, and increasing market integration in the Cape Colony. 

The first case considers the South African art market. This chapter explores aggregation methods to estimate South African art price indices (2000Q1-2015Q4), using a relatively large database of art auction prices. The challenge in aggregating this microeconomic dataset is that artworks are largely unique and infrequently traded, which means that the quality of items sold is not constant over time. The chapter explores central tendency, hedonic and hybrid repeat sales methods to overcome this challenge to estimate quality-adjusted South African art price indices, which reflect the mean in the distribution of growth rates. The chapter then studies the estimated art price indices for evidence of a bubble in South African art prices, by testing the hypothesis that South African art prices exhibited mildly explosive behaviour over the period.

The second case considers business sentiment in South Africa. This chapter explores aggregation methods to estimate indicators of business confidence and uncertainty for South Africa (1992Q1-2015Q3), using the Bureau for Economic Research's (BER) business tendency surveys. The challenge in aggregating this microeconomic dataset is to measure these nebulous concepts by identifying a pattern from the disparate views of individual agents. The chapter explores aggregation methods to capture the full distribution of the qualitative survey responses by calculating the cross-sectional weighted first and second moments (mean and variance) of the distribution of responses. The chapter estimates various measures of confidence, which reflect the first moment, and uncertainty, which reflect the second moment of the distribution. The chapter then examines the relationship between business sentiment and real activity in South Africa, by studying the leading indicator properties of the indicators, and testing the hypothesis that there was significant predictive comovement between the sentiment indicators and real GDP growth.

The third case considers historical commodity prices in the Cape Colony. This chapter explores aggregation methods to estimate monthly commodity price indices for the Cape Colony (1889/10-1914/08), using a high-frequency dataset on commodity prices in various towns in the Colony. The challenge in aggregating this dataset is that the records are incomplete with substantial gaps in the individual series. The chapter uses the repeat sales method to aggregate the incomplete data to form relatively continuous time series, which reflect the mean in the distribution of growth rates. The chapter then studies the estimated price indices, as well as cross-sectional moments in the distribution, for evidence of increasing internal market integration, by testing the hypothesis that prices were converging in the Cape Colony over this period.

The three chapters follow the same structure. Each chapter demonstrates the use of techniques to overcome the data challenges in aggregating relatively large microeconomic datasets. Each chapter then estimates and presents a set of macroeconomic indicators: art price indices, sentiment indices, and wholesale commodity price indices. The internal validity of the indicators is assessed by comparing measures calculated with different methodologies. The external validity of the indicators is assessed by testing their conformity to similar existing measures, when available. Each set of indicators is evaluated according to a specific criterion appropriate in each setting (i.e. smoothness, tracking record, and the quantity theory), to assess which are the superior indicators. Finally, each chapter uses the estimated indicators to test a specific hypothesis (i.e. explosive prices, predictive comovement, and market integration). This illustrates how the indicators might be used to aid economic analysis in each setting. 

##Objectives and Contributions
This dissertation contributes to the literature by demonstrating useful techniques to overcome specific challenges in aggregating relatively large microeconomic datasets to estimate macroeconomic time series indicators. The specific shortcomings involve compositional changes over time, capturing the full distribution of qualitative responses, and incomplete coverage of high-frequency historical records. In some cases these techniques are applied to the South African setting for the first time. 

These aggregation techniques may prove useful in a variety of research settings that present similar challenges. The hedonic and hybrid repeat sales methods employed in this dissertation would be useful in constructing indices for other unique assets, such as real estate, antiques and wine, where there is a lack of repeat sales and the quality-mix of items differs over time. International real estate price indices often employ the repeat sales or hedonic methods to calculate quality-adjusted price indices. The repeat sales method, for instance, is used to calculate the S&P/Case-Shiller Home Price Indices in the US. In South Africa, ABSA, FNB and Standard Bank currently only use stratified central tendency methods to construct their property price indices. As demonstrated below, the central tendency method does not adequately control for quality-mix changes. Using the repeat sales or hedonic methods would substantially improve upon real estate price indices in South Africa. Moreover, these techniques may be used to calculate the first quality-adjusted prices indices for other unique items, such as wine and antiques, as more comprehensive microeconomic datasets become available.

The weighted cross-sectional moments of qualitative responses employed in this dissertation would be useful in other applications with qualitative survey responses, such as consumer surveys, where there are challenges capturing the full distribution of responses. Consumer confidence measures are popular indicators and calculated all over the world, often using qualitative surveys. Popular international confidence indicators include the European Commission's Economic Sentiment Index and the University of Michigan consumer confidence measure for the US. The BER calculates consumer confidence using their consumer tendency surveys. Using the techniques demonstrated below, it would be possible to improve on the existing measures of consumer confidence, by capturing the more of the richness in the data. Moreover, it would be possible create new measures of consumer uncertainty, by calculating the weighted cross-sectional dispersion in responses. These indicators may be useful for forecasting and as leading indicators of the cycle in real activity.

The repeat sales method employed in this dissertation may prove useful in a diverse range of applications where the information is incomplete. Historical data, and higher-frequency records in particular, often suffer from missing observations, which makes it challenging to form continuous series. The techniques demonstrated below provide a simple and consistent way to overcome some of the problems with aggregating incomplete information from various sources. It may be useful to aggregate information on, for example, wages or incomes, especially when the information from various sources can be combined to create relatively continuous series. These aggregation techniques may become increasingly useful as more historical information is digitised and transcribed and becomes available for research.

Each chapter applies the aggregation techniques to create useful macroeconomic time series from the relatively large microeconomic datasets. The macroeconomic time series are intended to establish stylised facts in each of the three fields, and, where applicable, improve upon existing measures. The art prices indices are the first price indices for South African art. The confidence and uncertainty measures improve upon existing measures of business confidence and uncertainty in South Africa. The historical commodity price index is the first monthly index for the period (1889-1914), and provides an improved measure of inflation for the Cape Colony. 

The time series are then used to answer a specific question in each chapter. The art price indices are studied for evidence of a bubble in South African art prices. The tests indicate that South African art prices exhibited mildly explosive behaviour over the period. The business sentiment indicators are studied for evidence of significant comovement with real economic activity in South Africa. The tests indicate that there was significant comovement between the sentiment indicators and real GDP growth over the period. The historical commodity price indices are studied for evidence of increasing internal market integration. The tests indicate that prices in the towns of the Cape colony were converging, and in some cases cointegrated, over this period.

The specific questions addressed in the dissertation are the following: 

1. Art Prices:

    1.1.	How do we aggregate auction prices for unique artworks to construct quality-adjusted art price indices? 

    1.2.	What happened to South African art prices over time? 

    1.3.	Is there evidence of a bubble in art prices over the period?

2. Business Sentiment:

    2.1.	How do we aggregate qualitative business tendency surveys to construct sentiment indicators that capture the full distribution of responses? 

    2.2.	What happened to business confidence and uncertainty in South Africa over time? 

    2.3.	Is there evidence of significant comovement between the sentiment indicators and real activity?

3. Historical Commodity Prices:

    3.1.	How do we aggregate high-frequency prices with missing values to construct commodity price indices? 

    3.2.	What happened to wholesale prices in the Cape Colony over time? 

    3.3.	Is there evidence of increasing market integration over the period?

Each chapter suggests potential future research where the indicators may prove useful. To aid further research in each field, the time series indicators are reported in the appendix of each chapter. The rest of the Introduction presents brief chapter summaries.

##Art Prices
Contemporary African art has experienced a surge in popularity over the last few decades. The South African art market in particular has grown markedly, both in terms of the number of transactions and total turnover [@Fedderke2014]. Yet to date there has been little research on the South African art market and particularly trends in art prices. This is, at least in part, due to a lack of data on art prices [@Campbell2009]. It is important to analyse price movements over time in order to understand the development and the dynamics of the market. 

Estimating accurate price indices for unique items such as artworks can be challenging [@Jiang2014]. Artworks are typically sold relatively infrequently. This means that that only a small sample of market prices are observed at any given time. Artworks are also typically unique. This means that the composition of the sample of artworks observed will generally differ between periods, making it difficult to compare prices over time [@Hansen2009]. These features present challenges to measuring the state of the market over time.

The primary aim of this chapter is to explore methods to construct quality-adjusted South African art price indices, using a relatively large database of auction prices. This is the first price index for South African art, of the type often estimated internationally (e.g. @Mei2002, @Renneboog2002, and @Kraussl2010). The indices reflect the first moment of the distribution in the growth rates in art prices, while adjusting for quality-mix or compositional changes over time.

The chapter uses three broad methodologies to develop price indices for South African art: central tendency, hedonic and hybrid repeat sales methods. Simple central tendency indices are estimated as a baseline to compare the results from the different methodologies. The chapter argues that central tendency measures do not adequately control for compositional changes over time. Various indices are estimated with the hedonic regression method, which is able to control more adequately for quality-mix changes by attributing implicit prices to a set of characteristics. The hedonic indices paint a relatively consistent picture of the trend in South African art prices over time. The main shortcoming of the hedonic method is that it has potential omitted variable bias, which might bias the indices. 

The repeat sales method provides an alternative estimation method for quality-adjusted price indices. Repeat sales indices suffer less from potential omitted variable bias, but have the shortcoming of potential sample selection bias. The repeat sales method controls for quality-mix changes by tracking the same asset over time. Hence, it utilises only artworks that have been traded more than once. The scarcity of repeat sales observations in the database limits the usefulness of the classical repeated sales approach in this case. The chapter proposes a new hybrid repeat sales method as an alternative, in the spirit of the pseudo-repeat sales method in @Guo2014. It addresses the problem of limited repeat sales observations and, to some extent, the potential omitted variable bias inherent in the hedonic method.

The internal validity of the indicators is assessed by comparing the indices calculated with the different methodologies. In this way, the indices estimated with the pseudo-repeat sales approach acts as a type of internal validity test, to check that the results are not driven by the inherent biases of a specific method. The indices estimated with the hedonic and pseudo-repeat sales methods point to the same general trend in South African art prices. This implies that potential omitted variable bias inherent in the hedonic method and the sample selection bias inherent in the repeat sales method are not dictating the results [@Calomiris2016]. The indices estimated with the hedonic and pseudo-repeat sales methods differ markedly from the central tendency indices, which demonstrates the importance of adjusting for quality-mix changes when producing price indices.

The external validity of the indices is assessed by testing their conformity to similar existing measures. In the absence of another South African art price index, the indices are compared to prices indices of other South African assets (such as stocks and real estate). As will be shown, available international art prices provide another external validity check for the South African art price indices. The trends in the South African art prices seem plausible, although they exhibit a more dramatic price increase in the run-up to the financial crisis than the other assets. 

The indices are then evaluated directly in terms of smoothness or signal-to-noise metrics (i.e. lower random noise), in order to assess which index provides the most accurate measure of South African art prices over time. The smoothness metrics suggest that the 1-year adjacent period hedonic index is the most accurate, although all of the versions of the hedonic and pseudo-repeat sales indices provide similar results. 

The secondary aim of this chapter is to study the estimated art price indices for evidence of a bubble in South African art prices. According to the price indices there was a large increase in South African art prices in the run-up to the Great Recession. The chapter follows @Kraussl2016 in using the bubble detection tests developed by @Phillips2011. The approach is based on a right-tailed augmented Dickey-Fuller (ADF) unit root test, which can detect explosive behaviour directly in time series. The approach is used to test the hypothesis that South African art prices exhibited mildly explosive behaviour over the period.

The results indicate that there is evidence of bubble-like behaviour in all of the hedonic and pseudo-repeat sales art price indices. These indices provide relatively consistent results in terms of the explosive periods in the South African art market, with a potential bubble most likely beginning in 2006 and ending in 2008. The bubble detection tests performed on the different market segments indicate that the bubble process was relatively dispersed throughout the market, although prices seem to have been especially explosive for high-end oil paintings by the top artists. 

The chapter argues that the hedonic and pseudo-repeat sales approaches are useful aggregation techniques for unique items that are infrequently traded, where the quality-mix of items is not constant over time. These approaches produce indices that improve upon the more common central tendency indices. The quality-adjusted indices indicate that there was a large increase in South African art prices in the run-up to the Great Recession. The bubble detection tests indicate that there is evidence of mildly explosive prices in the South African art market, with a potential bubble from 2006 to 2008. 
 
##Business Sentiment
The global financial crisis and subsequent Great Recession were associated with exceptionally low levels of confidence and heightened uncertainty [@ECB2013]. The idea that weak business sentiment influenced economic activity has motivated a large body of literature investigating the impact of changes in business sentiment, and especially uncertainty, on real economic activity. To date there has been little research on business sentiment in South Africa. It is important to confirm the existence and nature of the relationship between sentiment and economic activity in developing countries, which often face higher uncertainty than developed countries [@Bloom2014].

Business sentiment refers to two separate concepts, namely *confidence* and *uncertainty*. Both are elusive concepts that are difficult to define precisely or measure directly [@Santero1996]. The imprecise definition of confidence and uncertainty makes it difficult to construct proxies and calls for various measures of both concepts. Although measuring business sentiment is not straightforward, survey-based indicators can be helpful in discovering agents' opinions on future economic developments [@OECD2003]. Survey-based measures have the advantage that they are derived from opinions of key economic agents [@Girardi2015], are available earlier than official statistics, and are usually not subject to revision [@ECB2013]. The challenge in aggregating the microeconomic data from the BER business tendency surveys is to identify an underlying pattern from the disparate views of individual agents. 

The primary aim of this chapter is to explore aggregation methods to capture the full distribution of the qualitative survey responses, by calculating the first and second weighted cross-sectional moments of the distribution. The composite indicators of business confidence and uncertainty are based on these moments. Two composite confidence indicators are calculated as the cross-sectional mean of responses to questions on current and expected future business conditions [@OECD2003]. Three composite uncertainty indicators are calculated as the cross-sectional dispersion of forward-looking responses and the cross-sectional mean and dispersion of individual firm expectation errors [@Arslan2011; @Bachmann2013; @Girardi2015]. 

Only two business confidence indicators are regularly published for South Africa: the South African Chamber of Commerce and Industry Business Confidence Index (SACCI BCI) and the RMB/BER Business Confidence Index (BER BCI). The SACCI BCI is a composite measure of economic activity, rather than a confidence indicator in the way it is defined in the literature. The BER BCI is a measure of confidence derived from the BER's business tendency surveys [@Kershoff2015]. The BER BCI is based on a single question on current conditions. The survey responses are weighted in an ad hoc manner and the services sector survey is excluded from the calculation. Only a few studies have created proxies for uncertainty in South Africa (e.g. @Redl2015 and @Hlatshwayo2016). The existing proxies capture different aspects of uncertainty, but none has fully exploited the information contained in the BER business tendency surveys to measure business uncertainty in South Africa. 

The new composite indicators attempt to improve on the existing measures of sentiment for South Africa, by incorporating more of the available information from the qualitative business tendency surveys. The composite indicators incorporate the survey responses from a number of questions, maintaining a distinction between current and expected future conditions. The responses are weighted to produce sectoral and aggregate indicators, which are analysed separately. The indices also incorporate the services sector, which is not included in the BER BCI. Whereas the previous chapter constructed various quality-adjusted measures of the mean of the distribution of growth rates, this chapter calculates various measures of the mean and variance of survey responses, as proxies for confidence and uncertainty.

The internal and external validity of the indicators are assessed by comparing the different composite indicators to each other, and to the existing measures of confidence and uncertainty in South Africa. The two confidence indicators are compared to the BER BCI and the SACCI BCI, while the three composite uncertainty indicators are compared to a measure of financial market uncertainty and the economic policy uncertainty indicator created by @Hlatshwayo2016. In addition, the chapter constructs an overall composite measure of uncertainty, which combines the survey-based uncertainty indicators with the measures of financial market and economic policy uncertainty.

The sentiment indicators are then evaluated according to their comovement with real GDP growth (i.e. their tracking record), in order to assess whether they are able to improve upon the existing indicators. The new composite confidence indicators exhibit a significant positive correlation with real GDP growth. The measure based on current conditions tracks real GDP growth better than existing measures. The leading indicator properties of the confidence indices are also evaluated, in terms of the timing of turning points and concordance with the official SARB business cycle. The indicators provide advanced warning of turning points in the business cycle, which implies that they may be useful for monitoring economic developments in a timely manner. The composite uncertainty indicators exhibit a significant negative correlation with real GDP growth, albeit at different horizons. The most plausible proxy for uncertainty is the combined indicator, as it seems to reflect key economic events and exhibits a higher negative correlation with real GDP growth rates than the individual indicators. 

The secondary aim of this chapter is to examine the relationship between business sentiment and real economic activity in South Africa, by testing the hypothesis that there is significant predictive comovement between the sentiment indicators and real GDP growth, using the standard VAR framework. There has been very little analysis of the impact of business sentiment on real economic activity in the South African context (e.g. @Pellissier2002 and @Redl2015). The relationship between the indicators and real GDP growth is investigated, including the timing of this relationship and the extent to which correlation is conditional on other economic variables. 

The results suggest that the survey-based confidence indicators contain relevant information for predicting output growth. The impulse response analysis suggests that a positive shock to the confidence indicators was followed by a significant increase in real GDP growth. This was the case for the aggregate indicators as well as the sectoral indicators. This implies that the confidence indicators are potentially useful for forecasting future economic activity. The impulse response analysis suggests that a positive shock to uncertainty is followed by a decrease in real GDP growth. The combined composite uncertainty indicator, which incorporates multiple sources of uncertainty, exhibits a stronger relationship with real GDP growth than any of the individual measures.

The chapter argues that the first and second weighted cross-sectional moments of a number of survey responses are useful to identify an underlying pattern from the disparate views of individual agents, to create proxies for business confidence and uncertainty. This approach produces composite indicators that improve upon the existing measures. Overall the evidence indicates that there is significant comovement between the indicators and economic activity, and that they contain potentially useful predictive information. The findings are robust to the inclusion of additional economic variables. The impact of shocks to the sentiment indicators are larger on real production and investment growth than on real GDP growth, as theory would predict [@Bloom2009].

##Historical Commodity Prices
Over the past two decades the increase in access to online resources and inexpensive computing power sparked a data revolution in African economic history [@Fourie2016]. Scholars have been able to capture and analyse historical statistics on a much larger scale than before. Higher frequency records are especially useful, as they allow a more detailed investigation of price histories, business cycles, and market behaviour in general [@Mitchell2012]. Historical statistics, and higher-frequency records in particular, often contain substantial gaps, which makes aggregation challenging [@Klovland2014a]. 

The primary aim of this chapter is to explore aggregation methods to develop relatively continuous monthly wholesale commodity price indices for the Cape Colony. The indices are based on an expanded version of the historical dataset of monthly market prices from 1889 to 1914 used in @Boshoff2017. The dataset consists of monthly market prices of various agricultural products in several towns reported in the Agricultural Journals of the Department of Agriculture. The analysis is supplemented by incorporating annual market prices for various agricultural products in several towns reported in the Cape Colony Blue Books. This allows the inclusion of a number of important products, such as wool and hides, which are omitted from the Agricultural Journals. The challenge in aggregating the datasets is that both sets of records are incomplete, in terms of the coverage of both products and towns.

@Klovland2014a showed that the repeat sales method, which is typically used to create indices for infrequently traded items, such as artworks, may be used to deal with incomplete data in this context. The chapter demonstrates the use of the repeat sales method to aggregate the incomplete data to form relatively continuous time series. The repeat sales method provides a consistent way to aggregate the price data and produces indices with substantially fewer gaps than there are in the individual series. The repeat sales method is similar to the hedonic and hybrid repeat sales methods used in chapter 2, in that it calculates the mean in the distribution of the growth rates.

The chapter applies the repeat sales method to estimate monthly wholesale commodity price indices for a number of individual products. The product indices are then aggregated to form indices of broader product groups, as well as a total commodity price index. The weights are based on production values reported in the 1904 census, as well as import values reported in the Blue Books. The price indices correspond well with the historical narrative on the economic history of the Cape Colony, with a large increase before and during the Second South African War (1899-1902) and a large decrease up to Unification (1910).

Following @Ruch2016, the high-frequency prices are used to gain some insight into the pricing behaviour over this period (i.e. the size and frequency of price changes). This information is used to calculate a simple alternative measure of overall inflation, which is provides an internal validity check for the overall wholesale commodity price index.

In order to gauge the external validity of the price indices, the chapter tests conformity to existing measures of the price level. In the absence of an existing monthly commodity price index for the Cape Colony over the period, the price indices are compared the annual consumer price indices (CPIs) estimated by @DeZwart2011. As will be shown, available wholesale price indices for the UK and the US provide another external validity check for the wholesale price indices. The indices are then evaluated by their conformity to the path implied by available monetary aggregates. The total price index seems to better reflect the monetary history of the Cape Colony than the existing CPIs. 

The secondary aim of the chapter is to use the price indices, as well as other aggregate measures, to investigate internal market integration in the Cape Colony. There is a large international literature on market integration, but very few studies have considered internal market integration in the Cape Colony around the turn of the 20th century (e.g. @Boshoff2017). During this period the mineral revolution led to the rapid expansion of the railway network and created a potentially large internal market [@Schumann1938].

Market integration concerns the convergence of prices for the same goods are throughout the economy [@Andrabi2010], as well as the efficiency with which price gaps return to equilibrium after a shock [@Federico2013]. This part of the chapter builds on the work of @Boshoff2017, by expanding the period and the number of products, and considering on both dimensions of market integration (i.e. convergence and efficiency). 

The chapter studies measures of cross-sectional price dispersion between the towns in the Cape Colony, as well as regional wholesale price indices, for evidence of increasing internal market integration. The chapter test the hypotheses that price dispersion between towns was declining over the period and that regional prices indices were cointegrated. The cross-sectional measures of price dispersion, such as the coefficient of variation, are related to the measures used in chapter 3. According to these measures many of the commodity prices were converging over the period, and a number of regional commodity price indices were cointegrated over the period. This implies that there was increasing market integration between towns in the Cape Colony, in all likelihood aided by the rapid development of the railway network.

The chapter argues that the repeat sales approach is a useful technique for aggregating incomplete information from various sources. This approach produces a proxy for inflation that improves upon the existing measures. The price indices correspond well with the economic history of the Cape Colony. The results indicate that there is evidence of market integration over the period, with declining price dispersion between towns and cointegrated regional price indices for a number of products.

##Summary
The primary aim of the dissertation is to demonstrate methods to overcome specific challenges in aggregating relatively large microeconomic datasets to create macroeconomic time series. The three datasets have specific shortcomings, which make it challenging to estimate time series indicators. The aggregation techniques are applied and the time series indicators are presented. The internal and external validity of the indicators are assessed and the indicators are evaluated according to an appropriate criterion. The time series indicators and reported in the appendix of each chapter.

The secondary aim of the dissertation is to use the time series to test a specific hypothesis in each case. The results in chapter 2 show that there is evidence of explosive price behaviour in South African art prices. Chapter 3 presents evidence of predictive comovement between the sentiment indicators and real GDP growth. The results in chapter 4 indicate that there is evidence of increasing market integration in the Cape Colony. The final chapter summarises the findings of the dissertation, recaps the research contribution, and suggests potential further research where the indicators may prove useful.

