---
output: 
    pdf_document:
        fig_caption: yes
        number_sections: true
---

#Conclusion
Large microeconomic datasets are becoming increasing available, due to technological developments, and will become more commonplace in the future. These datasets provides an opportunity to improve on the measurement of a range of economic phenomena and to bolster economic research [@Schutt2013]. One way in which these large amounts of data can aid economic analysis is to construct better macroeconomic indicators. There are always challenges in aggregating this information.

The primary aim of this dissertation was to explore aggregation methods that overcome specific challenges in three relatively large microeconomic datasets. Each dataset has specific shortcomings, namely compositional changes, capturing the full distribution of qualitative responses, and incomplete coverage, which make it challenging to estimate time series indicators. The dissertation demonstrated aggregation and estimation techniques, such as the hedonic and repeat sales methods and weighted cross-sectional moments, to create useful macroeconomic indicators. 

The secondary aim of the dissertation was to use these macroeconomic indicators to test a specific hypothesis in each case: mildly explosive South African art prices; significant predictive comovement between sentiment and real activity in South Africa; and increasing market integration in the Cape Colony.  

##Art Prices
The primary aim of this chapter was to explore methods to construct quality-adjusted South African art price indices, using a relatively large dataset of auction prices. Estimating accurate indicators for unique items such as artworks can be challenging. Artworks are typically unique and sold infrequently, which means that the composition or quality-mix of items sold is not constant over time [@Hansen2009].
This chapter used three broad methodologies to develop price indices for South African art: central tendency methods, hedonic methods and hybrid repeat sales methods. The chapter argued that central tendency measures do not adequately control for compositional changes over time. Various indices were estimated with the hedonic regression method, which is able to control more adequately for quality-mix changes by attributing implicit prices to a set of asset characteristics. The main shortcoming of the hedonic method is that it has potential omitted variable bias, which might bias the indices. The scarcity of repeat sales observations in the dataset limited the usefulness of the classical repeated sales approach in this case. The chapter therefore proposed a simple new hybrid or pseudo-repeat sales methodology, which acted as an internal validity test. This approach addressed to some extent the problem of scarcity of repeat sales and the potential omitted variable bias inherent in the hedonic method [@Guo2014].

The indices estimated with the regression-based methods pointed to the same general trend in South African art prices, which provides some confidence that potential omitted variable bias and sample selection bias are not pervasive in this case [@Calomiris2016]. The external validity of the indices was assessed by testing their conformity to prices indices of other South African assets and international art prices. The indices were evaluated in terms of smoothness metrics, which suggested that the 1-year adjacent period hedonic index performed the best, although the regression-based indices were similar. 

The secondary aim of the chapter was to study the estimated art price indices for evidence of a bubble. The direct bubble detection tests proposed by @Phillips2011 were used to investigate whether South African art prices exhibited mildly explosive behaviour over the period. The regression-based indices provided relatively consistent results in terms of the explosive periods in the South African art market, with a potential bubble most likely beginning in 2006 and ending in 2008. The process seemed to be relatively dispersed throughout the market, although prices seem to have been especially explosive for oil paintings by the top artists. 

Further research applications might consider the risk-return profile of art as an asset class, and evaluate whether art could form part of an optimal investment portfolio. Conventional wisdom says that the top artworks by established artists tend to outperform the rest of the market [@Mei2002]. This so-called Masterpiece effect could be investigated by examining different parts of the distribution of art prices. Potential drivers or factors that influence the fluctuations in art prices over time, such as wealth effects, might also be investigated. The quality-adjusted art price indices can facilitate these inquiries and enable one to be more concrete about developments in the South African art market.

##Business Sentiment
The primary aim of this chapter was to explore aggregation methods to create proxies for business sentiment in South Africa, using the microdata from the BER's business tendency surveys. Although measuring business sentiment is not straightforward, survey-based indicators can be helpful in discovering agents' opinions on future economic developments [@OECD2003]. Survey-based measures have the advantage that they are derived from opinions of key economic agents [@Girardi2015], are available with a shorter lag than official statistics, and are usually not subject to revisions [@ECB2013]. The challenge in aggregating the qualitative survey responses is to measure these concepts by identifying a pattern from the disparate views of individual agents. 

The chapter demonstrates aggregation methods to capture the full distribution of the qualitative survey responses by calculating the cross-sectional weighted mean and variance of the distribution. The chapter calculated composite indicators of business confidence and uncertainty, incorporating the survey responses from a number of questions on current conditions and expectations. The responses were weighted to produce sectoral indicators, including the survey of the services sector, as well as aggregate indicators. The composite confidence indicators were calculated as the cross-sectional mean of responses to questions on current and future conditions [@OECD2003]. The composite uncertainty indicators were calculated as the cross-sectional standard deviation of forward-looking responses and the cross-sectional mean and standard deviation in individual firm expectation errors [@Arslan2011; @Bachmann2013; @Girardi2015]. A composite overall measure of uncertainty was constructed, which combined the survey-based uncertainty indicators with financial market uncertainty and economic policy uncertainty. 

The internal and external validity of the indicators was assessed by comparing the different composite indicators to each other, and to the existing measures for South Africa. The chapter also constructed an overall composite measure of uncertainty, which combined the survey-based uncertainty indicators with the measures of financial market and economic policy uncertainty. The sentiment indicators were evaluated according to their comovement with real GDP growth (i.e. their tracking record). The new composite confidence indicator (Activity) exhibited a better tracking record (i.e. a higher correlation with real GDP growth) than existing measures. The overall composite uncertainty indicator exhibited a higher negative correlation with real GDP growth rates than the individual indicators. 

The secondary aim of this chapter was to examine the relationship between business sentiment and real economic activity in South Africa, by testing the hypothesis that there was significant comovement between the sentiment indicators and real GDP growth. The chapter tried to establish if there was a significant relationship between the indicators and real GDP growth, the timing of this relationship, and if it remained significant after taking other economic variables into account. Overall, the evidence indicated that there was at least strong comovement between the indicators and economic activity, and that they contained potentially useful predictive information.

In the VAR models, a positive shock to the confidence indicators was followed by a significant increase in real GDP growth. This was the case for the aggregate indicators as well as the sectoral indicators. This implies that these confidence indicators are potentially useful for monitoring economic developments in a timely manner and for forecasting future economic activity. Positive shocks to uncertainty were generally followed by a decrease in real GDP growth. The results from the larger VAR systems confirm the findings in the simple bivariate VARs. As the theory would predict, the impact of the shocks on real production and investment growth were larger and more significant [@Bloom2009]. 

A number of studies have estimated these larger systems in levels (e.g. @Bachmann2013), as opposed to the growth rates used in this dissertation. Further analysis could investigate larger systems in levels, which may allow longer term relationships to emerge. A related avenue for investigation would be to test whether there is asymmetry in the frequency horizon of shock effects. Deeper or systemic shocks may be associated with medium-term, rather than high-frequency fluctuations in output. An extension would be to test whether the relationship is non-linear or asymmetric, depending on the size or duration of the change in sentiment. The forecasting ability of sentiment indicators might be completely offset by other variables during ordinary times, while increasing notably in the presence of unusual events. Moreover, the relationship during a recovery phase may be different from the relationship during the rest of an expansion. Further analysis may try to determine whether there is a causal role for sentiment in the business cycle. It may also be instructive to determine what were the drivers or factors that influenced the sentiment indicators [@Bloom2014].

The evidence suggests that there is some potentially useful predictive information in the indicators. The indicators may therefore be useful in larger forecasting exercises. Future research may assess the usefulness of the indicators in improving out-of-sample forecasts. Significant in-sample evidence of forecasting power does not guarantee significant out-of-sample ability. The usefulness of the indicators for real-time forecasting may also be analysed, given that they are available around two months before many official series. As more data becomes available, the confidence indicators may be examined to see if they provide accurate early warning signals for business cycle turning points. The analysis could be expanded by analysing the cyclical properties of the indicators in terms of duration, amplitude and steepness. The new sentiment indicators may facilitate these inquiries.

##Historical Commodity Prices
The primary aim of this chapter was to explore aggregation methods to develop relatively continuous monthly wholesale commodity price indices for the Cape Colony. The monthly market prices reported the Agricultural Journals for various products in several towns were supplemented with annual market prices reported in the Cape Colony Blue Books. The challenge was that the data was incomplete, in terms of the coverage of both products and towns. 

The chapter demonstrated that the repeat sales method provides a consistent way to aggregate the incomplete price data and produces indices with substantially fewer gaps than in the individual series [@Klovland2014a]. The repeat sales method was used to estimate monthly wholesale commodity price indices for a number of individual products. The product indices were aggregated to form indices of broader product groups and a total wholesale commodity price index. The weights were based on production values reported in the 1904 census, as well as import values reported in the Blue Books. The wholesale price indices corresponded well to the historical narrative on the economic history of the Cape Colony. Overall prices followed a strong cyclical trend over the period, with a large increase before and during the Second South African War (1899-1902) and a large decrease up to Unification (1910). 

The high-frequency prices were used to analyse the size and frequency of price changes [@Ruch2016]. Monthly changes were dominated by zero or small changes, with around 86% of changes smaller than 10% in either direction. The frequency of price changes was relatively high, with the prices of goods changing on average every 50 days. This information was used to calculate a simple alternative measure of overall inflation, which was used as an internal validity check for the total WPI.  The external validity of the indices was assessed by testing their conformity to annual consumer price indices (CPIs) [@DeZwart2011], as well as monthly wholesale price indices for the UK and the US. The indices are then evaluated by their conformity to the path implied by available monetary aggregates. The total WPI provides a clearer picture of the inflation history of the period in that it reflects the monetary history better than the existing measures.

The secondary aim of the chapter was to use the aggregated measures to investigate internal market integration in the Cape Colony. This chapter built on the work of @Boshoff2017, by expanding the period and the number of products, and addressing the convergence of market prices. According to the measures of cross-sectional absolute price gaps and dispersion between the towns, many of the commodity prices were converging over the period. A number of regional price indices for specific products exhibited significant correlations and cointegration. This implies that there was increasing market integration between towns in the Cape Colony.

Further research might supplement the indices by including prices from other sources, and potentially import and export prices. The indices should improve as more data sources are added. Another extension would be to add prices from the other territories in South Africa, i.e. Natal, the Transvaal, and the Orange Free State, to compare the price histories of the four territories. 

Future research could also investigate convergence between towns along the main and branch railway lines, as more records for specific towns are added. An extension would be to apply other tests of market integration. The factors that aided the integration could also be investigated, as well as the impact of market integration on welfare and long term growth [@Federico2012]. The relatively continuous high-frequency price indices, as well as the underlying data, can facilitate these inquiries.

##Contributions
This dissertation has attempted to make three main contributions to the literature. The first was to explore suitable aggregation methods to overcome some of the challenges in aggregating the relatively large microeconomic datasets. The specific challenges were compositional changes in unique items sold over time, capturing the full distribution of qualitative responses, and incomplete coverage of historical records. The techniques included hedonic and hybrid methods in the chapter 2, weighted cross-sectional moments of the distribution in chapter 3, and the repeat sales method in chapter 4. Chapter 2 also proposed a simple new hybrid repeat sales method that to some extent addressed the lack of repeat sales in the sample and the potential omitted variable bias of the hedonic method. These aggregation techniques may prove useful in a variety of settings where there are similar challenges, especially as more data becomes available. 

The second contribution was to apply these techniques to overcome the data challenges to create useful macroeconomic time series indicators: art price indices, sentiment indices, and historical commodity price indices. The estimated time series are reported in the appendix of each chapter. The hope is that the indicators will prove useful for further research in each of these fields. Chapter 4 also digitised two large new sets of historical records on market prices in the Cape Colony. These new datasets will be of use to economic historians doing research on this period of the Cape Colony's history.

The third contribution was to use the time series indicators to test a specific hypothesis in each case: explosive South African art prices; significant predictive comovement between sentiment and real activity in South Africa, and increasing market integration in the Cape Colony. 

In chapter 2 the regression-based indices provided relatively consistent results in terms of the explosive periods in South African art prices, with a potential bubble most likely beginning in 2006 and ending in 2008. Further research may investigate the potential drivers of this bubble formation process. In chapter 3 the VAR models indicated that positive shocks to the confidence and uncertainty indicators were followed by a significant increase and decrease in real GDP growth respectively. Future research may investigate the usefulness of these indicators in out-of-sample forecasts, as well as the potential causal impact of sentiment on real activity. Chapter 4 found evidence of price convergence between towns for a number of commodities, as well as evidence of cointegration in regional price indices. Future research may investigate the factors that aided the integration, such as railway expansion, as well as the impact of market integration on welfare and long term growth.

The aggregation techniques demonstrated in this dissertation may become ever more useful as additional microeconomic datasets become available for economic analysis. In addition, the time series indicators may be easily updated over time as longer series become available.

